version: '3.9'

services:
  production:
    build:
      context: .
      dockerfile: Dockerfile
    image: thaleslj/organizandotudo.admin:latest
    restart: unless-stopped
    ports:
      - "5555:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - backend

networks:
  backend: